# Generated by Django 4.2.25 on 2025-11-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_mensagemcontato_alter_funcionarios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
    ]
