# Generated by Django 4.2.25 on 2025-11-17 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_cliente_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
    ]
